# These are supported funding model platforms

## Here it's found and help my project

github: #
patreon: ssyt
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: #
community_bridge: #
liberapay: # Replace with a single Liberapay username
issuehunt: SSYT-Solutions/SymfonyBlog #Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['paypal.me/staarki94']
